version: "3"

services:
  app_actions:
    container_name: cicd_actions
    restart: always
    build: .
    ports:
      - "3000:3000"
    links: 
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mongodatabase
    image: mongo
    ports:
      - 27017:27017