on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build and check repository
    runs-on: ubuntu-latest
    
    steps:

    - name: checkout main
      user: actions/checkout@master
