on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build and check repository
    runs-on: ubuntu-latest
    
    steps:

    - name: checkout main
      uses: actions/checkout@master
    
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          if [ -d "arithmetic_operations_logs" ]; then
            echo "si existe"
          else
            echo "NOT found."
          fi
